# fly.toml app configuration file generated for byboshop-9mkd3a on 2025-02-21T13:23:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'byboshop-9mkd3a'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
